# Generated by Django 4.2.10 on 2024-02-21 12:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateTimeField(auto_now=True)),
                ("image", models.ImageField(upload_to="images/")),
                (
                    "decription",
                    models.TextField(max_length=500, verbose_name="Описание"),
                ),
            ],
        ),
    ]
