# Generated by Django 4.2.10 on 2024-02-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0003_news_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="news",
            name="created_at",
        ),
        migrations.AlterField(
            model_name="news",
            name="time",
            field=models.DateField(auto_now=True),
        ),
    ]
