# Generated by Django 4.2.10 on 2024-02-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0002_alter_news_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="created_at",
            field=models.DateField(auto_now=True),
        ),
    ]
