# Generated by Django 4.2.10 on 2024-02-21 11:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ApplicationsForParticipants",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="ФИО")),
                ("email", models.EmailField(max_length=200, verbose_name="Email")),
                ("phone_number", models.IntegerField(verbose_name="Номер телефона")),
                ("description", models.TextField(verbose_name="Описание")),
            ],
        ),
    ]
