# Generated by Django 4.2.10 on 2024-02-21 11:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("participants", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationsforparticipants",
            name="email",
            field=models.EmailField(max_length=200, verbose_name="Почта"),
        ),
        migrations.AlterField(
            model_name="applicationsforparticipants",
            name="phone_number",
            field=models.IntegerField(
                help_text="Введите телефон клиента в формате: +996xxxxxxxxx",
                verbose_name="Номер телефона",
            ),
        ),
    ]
