# Generated by Django 4.2.10 on 2024-02-21 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Projects",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(verbose_name="Описание")),
                ("link", models.CharField(max_length=1000)),
                ("image", models.ImageField(upload_to="projectsimg/")),
            ],
        ),
    ]
